// A trivial program written using the ELF library.
// This program has no sections and implements the following code:

// | mov $1, %eax          ('_exit' system call)
//   mov $42, %ebx         (exit code)
//   int $0x80

// The purpose is to return with exit code 42.

caterwaul.clone('std seq llasm.elf')(function (require) {
  var bytes = caterwaul.llasm.elf32.trivial_code([0xc7, 0xc0, 1, 0, 0, 0,  0xc7, 0xc3, 42, 0, 0, 0,  0xcd, 0x80]);

  require('fs').writeFile('test/return-42', new Buffer(bytes.length) /se[seq[bytes *!b[_[bi] = b]]], fn_[require('fs').chmod('test/return-42', 0700)]);
})(require);

// Generated by SDoc 
